[package]
edition = "2021"
name = "lebai-sdk"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "lebai_sdk"

[features]
default = []
ffi_lua = ["mlua"]
ffi_py = ["pyo3"]

[dependencies]
cmod = {version = "0"}
futures-util = "0.3"
jsonrpsee-core = {version = "0.16.0", features = ["async-client"]}
jsonrpsee-ws-client = {version = "0.16.0"}
mlua = {version = "0.8", features = ["lua54"], optional = true}
once_cell = "1"
pyo3 = {version = "0.17", features = ["abi3-py37"], optional = true}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = {version = "1.12", features = ["full"]}
