[package]
edition = "2021"
name = "lebai_sdk"
version = "0.1.2"

[workspace]
members = [
  "proto",
]

[lib]
crate-type = ["cdylib"]
name = "lebai_sdk"

[features]
default = []
ffi_lua = ["cmod/ffi_lua", "mlua"]
ffi_py = ["cmod/ffi_py", "pyo3"]
ffi_wasm = ["cmod/ffi_wasm", "wasm-bindgen", "wasm-bindgen-futures"]
mdns = ["mdns-sd"]

[dependencies]
async-lock = "2"
cmod = {version = "0"}
futures-timer = "3"
futures-util = "0.3"
jsonrpsee-core = {version = "0.16.0"}
mdns-sd = {version = "0.5", default-features = false, features = ["async"], optional = true}
mlua = {version = "0.8", features = ["lua54"], optional = true}
proto = {package = "lebai-proto", path = "proto"}
pyo3 = {version = "0.17", features = ["abi3-py37"], optional = true}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
wasm-bindgen = {version = "0.2", optional = true}
wasm-bindgen-futures = {version = "0.4", optional = true}

[target.'cfg(target_family = "wasm")'.dependencies]
jsonrpsee-wasm-client = {version = "0.16.0"}
[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonrpsee-ws-client = {version = "0.16.0"}
once_cell = "1"
tokio = {version = "1", features = ["full"]}

[patch.crates-io]
