[target.armv7-unknown-linux-gnueabihf]
ar = "arm-linux-gnueabihf-gcc"
linker = "arm-linux-gnueabihf-gcc"
[target.aarch64-unknown-linux-gnu]
ar = "aarch64-linux-gnu-gcc"
linker = "aarch64-linux-gnu-gcc"
[target.riscv64gc-unknown-linux-gnu]
ar = "riscv64-linux-gnu-gcc"
linker = "riscv64-linux-gnu-gcc"
[target.riscv64gc-unknown-linux-musl]
ar = "riscv64-linux-musl-gcc"
linker = "riscv64-linux-musl-gcc"

[target.'cfg(target_os = "macos")']
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[env]
