[package]
authors = ["rise0chen<rise0chen@163.com>"]
description = "lebai proto"
edition = "2018"
keywords = ["protobuf"]
license = "MIT"
name = "lebai-proto"
repository = "https://github.com/lebai-robotics/lebai-sdk.rs"
version = "3.0.4"

[dependencies]
jsonrpsee = {version = "0.20", features = ["client-core", "macros"]}
pbjson = "0.5"
pbjson-types = "0.5"
prost = "0.11"
serde = {version = "1", default-features = false, features = ["derive"]}
serde_json = "1"

[build-dependencies]
pbjson-build = "0.5"
pbjsonrpc-build = "0.17"
tonic-build = "0.9"
