name: build
run-name: ci building
on: 
  workflow_dispatch: 
  push: 
   branches:
    - master
  
permissions:
  contents: read
  pull-requests: read

jobs:
 builds:
  strategy:
   matrix:
    python: [3.7]
    os: [ubuntu-latest, windows-latest]
    archit: [aarch64, x86_64]
    compiler: [gnu, msvc]
    include:
     - os: ubuntu-latest
       protoc: linux-x86_64
       target: unknown-linux
     - os: windows-latest
       protoc: win64
       target: pc-windows
    exclude:
     - os: ubuntu-latest
       compiler: msvc
     - os: windows-latest
       archit: aarch64

  runs-on: ubuntu-latest
  container: registry.cn-shanghai.aliyuncs.com/lebai/util:sdk_py
  steps:
   - name: checkout
     uses: actions/checkout@v3

   - name: check python version
     uses: actions/setup-python@v4
     with:
      python-version: ${{ matrix.python }}

  #  - name: install maturin
  #    run: pip install maturin

  #  - name: get protoc
  #    run: curl -o protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v21.11/protoc-21.11-${{matrix.protoc}}.zip

  #  - name: unzip protoc
  #    run: unzip protoc.zip

   - name: build
     uses: PyO3/maturin-action@v1
     with: 
      command: build
      args: --release
      target: ${{matrix.archit}}-${{matrix.target}}-${{matrix.compiler}}
