name: Build Rust
run-name: Rust building
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: cargo build --release --features mdns
