name: Build Wasm
run-name: Wasm building
on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        target: [web, nodejs, bundler]
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: wasm-pack build --release --target ${{ matrix.target }} -- --features ffi_wasm
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Lebai_WASM_SDK_${{ matrix.target }}
          path: ./pkg
      - name: Release
        if: ${{ contains(github.ref, 'tags/v') && matrix.target == 'bundler' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: wasm-pack publish
